name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'
      - 'requirements.txt'
      - 'dbt/**'

jobs:
  install-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3


    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # Run Airflow tasks
    #- name: Set up Airflow
     # run: |
        # Install Astronomer CLI (astro)
    #    curl -sSL https://install.astronomer.io | sudo bash
    #    sudo mv /usr/local/bin/astro /usr/bin/astro
    #    astro airflow init

    # Deploy DAG
    #- name: Deploy Airflow DAG
    #  run: |
     #     cd dags
      #    astro deploy

    # Run DBT models
    #- name: Run DBT models
    #  run: |
    #      cd dbt
     #     dbt run

      
